### ISSUE TITLE
error al hacer deploy

### ISSUE THREAD

**Issue by alu0100505078** [ULL-ESIT-SYTW-1617/gitbook-start-heroku-ericlucastania#5]
Hola chicos, a la hora de hacer el deploy me da el siguiente error 

![image](https://cloud.githubusercontent.com/assets/14938442/20117537/f93078b8-a5f8-11e6-916a-71fd07e9a58b.png)

Todo lo anterior funciona pero al hacer el deploy y el siguiente paso que es el gulp deploy-heroku da errores. Avisadme en clase si les funciona

**Comment by alu0100785265** [comment]
Creo que eso se debe a que no está instalado el heroku toolbet.
