### ISSUE TITLE
Repositorio de github-api

### ISSUE THREAD

**Issue by Losnen** [ULL-ESIT-SYTW-1617/gitbook-start-heroku-ericlucastania#6]
Tienen el Repositorio  https://github.com/ULL-ESIT-SYTW-1617/crear-repositorio-en-github-ericlucastania-1 en privado , haganlo público para poder corregirles la práctica, gracias.

**Comment by alu0100785265** [comment]
ya está público,muchas gracias por avisar :) :+1:
