### ISSUE TITLE
No termina de desplegar en heroku

### ISSUE THREAD

**Issue by DanielRamosAcosta** [ULL-ESIT-SYTW-1617/gitbook-start-heroku-ericlucastania#9]
# tl;dr

Cuando se ejecuta el comando para desplegar, después de preguntar si necesitamos autenticación, se lanza un error de `UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Expected response to be successful, got 422`, y no crea la aplicación en heroku.

```
node -v; npm -v
v7.1.0
3.10.9
```

# Pasos

1. `npm i -g gitbook-start-elt`
2. `gitbook-start --dir correccionLucas`
3. `cd correccionLucas`
4. `git add .; git commit -m "Primer commit"`
5. `ls -la`

   Salida:

   ```
   total 40
   drwxr-xr-x 5 daniel daniel 4096 nov 23 13:56 ./
   drwxrwxr-x 7 daniel daniel 4096 nov 23 13:56 ../
   -rw-r--r-- 1 daniel daniel   88 nov 23 13:56 book.json
   drwxr-xr-x 8 daniel daniel 4096 nov 23 13:57 .git/
   -rw-r--r-- 1 daniel daniel  247 nov 23 13:56 gulpfile.js
   -rw-r--r-- 1 daniel daniel 1701 nov 23 13:56 package.json
   -rw-r--r-- 1 daniel daniel  237 nov 23 13:56 README.md
   drwxr-xr-x 2 daniel daniel 4096 nov 23 13:56 scripts/
   drwxr-xr-x 2 daniel daniel 4096 nov 23 13:56 txt/
   -rw-r--r-- 1 daniel daniel    6 nov 23 13:56 VERSION
   ```

6. `npm i -g gitbook-start-plugin-heroku-ericlucastania`
7. `gitbook-start -d heroku`

   Borro **Todas** las aplicaciones de heroku, y saco el token en mi cuenta.

   Salida:

   ```
   Introduzca el token para conectarte: d7c6825e-90c8-4983-a381-b90dc8aa1923
   correccionLucas@0.0.1 /home/daniel/Documentos/Repos/Ajenos/correccionLucas
   └─┬ gitbook-start-plugin-heroku-ericlucastania@1.0.95
     ├── async@1.5.2
     ├─┬ body-parser@1.15.2
     │ ├── bytes@2.4.0
     (...)
     └─┬ shelljs@0.7.5
       ├─┬ glob@7.1.1
       │ ├── fs.realpath@1.0.0
       │ ├─┬ inflight@1.0.6
       │ │ └── wrappy@1.0.2
       │ ├─┬ minimatch@3.0.3
       │ │ └─┬ brace-expansion@1.1.6
       │ │   ├── balanced-match@0.4.2
       │ │   └── concat-map@0.0.1
       │ ├── once@1.4.0
       │ └── path-is-absolute@1.0.1
       ├── interpret@1.0.1
       └─┬ rechoir@0.6.2
         └── resolve@1.1.7

   Introduzca el nombre de la aplicación: correccionLucas
   ¿Quiere solicitar autentificación para que los usuarios puedan acceder a su libro?(s/n): s
   (node:23357) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Expected response to be successful, got 422
   (node:23357) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
   ```

**Comment by alu0100786330** [comment]
Asegúrate de copiar el token sin espacios. Cuidado con los espacios del final de línea al copiar el token.

**Comment by DanielRamosAcosta** [comment]
He vuelto a hacerlo teniendo especial cuidado al pegar el token, pero me da exactamente el mismo error, el 422. 

Según la [API de heroku](https://devcenter.heroku.com/articles/platform-api-reference#client-error-responses) podría ser porque los parámetros que se le están pasando no son válidos. Una posible solución podría ser ver qué parámetros se le están pasando al `heroku-client`, y capturar el error de la promesa con `.catch` para ver qué puede estar pasando.

**Comment by DanielRamosAcosta** [comment]
Al final era que el nombre de la aplicación de heroku no puede contener mayúsculas. Todo funcionó bien al final :+1:
